### ISSUE TITLE
Обновление пакета на v2.4

### ISSUE THREAD

**Issue by greal** [gladyshev/yandex-direct-client#10]
Добрый день! 

Возникла проблема с обновлением пакета на версию 2.4

Composer пишет что установлена версия 2.4, а по факту установлена версия 2.3. Ни разу с таким не сталкивался, кеш composer чистил. Не подскажите, что я делаю не так?

**Comment by gladyshev** [comment]
Похоже проблема с вашим окружением, у себя не смог это воспроизвести. Если проблема еще актуальна дайте больше входной инофрмации. Версия компосера? Как выглядит запись в composer.json? Какая версия php?

**Comment by greal** [comment]
Здравствуйте! 
В данный момент запись в composer.json имеет следующий вид:

```
....
"php": ">=7.1.3",
"gladyshev/yandex-direct-client": "^2.4",
...
```

Версия:

```
Composer version 1.8.0 2018-12-03 10:31:16
```

Версия php:
```
PHP 7.2.10-0ubuntu0.18.04.1
```

**Comment by gladyshev** [comment]
Воспроизвести все равно не удалось. Пушнул новый релиз 2.4.1 это должно помочь, если проблема с кэшами у тебя, к тому же в 2.4.0 был критичный баг. Надо этот релиз удалить.

**Comment by greal** [comment]
@gladyshev да, сейчас все обновилось без проблем. Спасибо!
